apiVersion: v1
kind: Pod
metadata:
  name: python-web-server 
spec:
  containers:
    - name: python-web-server 
      image: python
      command: ["python", "app.py"]
      args: ["--debug"]
      resources:
        limits:
          memory: "64Mi"
          cpu: "250m"