apiVersion: v1
kind: Pod
metadata:
  name: sample-app
  labels:
    tier: backend
spec:
  containers:
    - name: main-app-container
      image: apache
      resources:
        limits:
          memory: "64Mi"
          cpu: "10m"
  initContainers:
    - name: sleep-container
      image: ubuntu
      command:
        - sleep
        - "1000"