apiVersion: v1
kind: Pod
metadata:
  name: yellow
  labels:
    name: yellow
spec:
  containers:
  - name: lemon
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: gold
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
