apiVersion: v1
kind: Pod
metadata:
  name: my-secret-app
  labels:
    name: my-secret-app
spec:
  containers:
  - name: my-secret-app
    image: ubuntu
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    envFrom:
      - secretRef:
          name: app-secret
