apiVersion: v1
kind: Pod
metadata:
  name: busy-box-pod
  labels:
    name: busy-box-pod
spec:
  schedulerName: my-custom-scheduler
  containers:
    - name: busy-box-pod
      image: busybox
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"