apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: webapp
    tier: frontend

spec:
  containers:
    - name: nginx
      image: nginx:alpine
      resources:
        limits:
          cpu: "1"
          memory: "200Mi"
      volumeMounts:
      - name: local-pv
        mountPath: /var/www/html
  volumes:
    - name: local-pv
      persistentVolumeClaim:
        claimName: local-pvc