apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp
    tier: frontend

spec:
  containers:
    - name: webapp-container
      image: kodekloud/event-simulator
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
      volumeMounts:
      - name: pvc-storage
        mountPath: /log
  volumes:
    - name: pvc-storage
      persistentVolumeClaim:
        claimName: claim-log-1